### ISSUE TITLE
我在portainer上一栈部署的，访问是白板 请问怎么解决

### ISSUE THREAD

**Issue by lonrencn** [ischenliang/quickly-picture-bed#30]
```
version: '3.7'

services:
  picServerV2:
    image: itchenliang/pic-server-v2
    container_name: picServerV2
    networks:
      - pic-net
    ports:
      - "4000:4000"
    environment:
      - DB_USERNAME=lig*****
      - DB_PASSWORD=********
      - DB_HOST=********
      - DB_PORT=3306
      - DB_DATABASE=lig*****
      - APP_PORT=4000
      - NPM_REGISTRY=https://registry.npmmirror.com
    volumes:
      - ~/lightfastpicture/public:/server/public

  picClientV2:
    image: itchenliang/pic-client-v2
    container_name: picClientV2
    networks:
      - pic-net
    ports:
      - "9099:80"


networks:
  pic-net:
    external: true # 告诉Docker Compose使用外部网络
    name: pic-net # 确定外部网络的名称
```
sever logs:

Executing (default): SELECT `id`, `website`, `contact`, `system`, `uplog`, `bucket_service`, `createdAt`, `updatedAt` FROM `setting` AS `Setting` LIMIT 1;

client logs:

64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" "-"
192.168.1.136 - - [17/May/2024:17:44:56 +0000] "GET /echarts.js HTTP/1.1" 200 3334642 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" "-"
192.168.1.136 - - [17/May/2024:17:44:56 +0000] "GET /favicon.ico HTTP/1.1" 200 16958 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" "-"
192.168.1.136 - - [17/May/2024:17:44:56 +0000] "POST /v1/setting/default HTTP/1.1" 200 55 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" "-"

****数据库是通的

![image](https://github.com/ischenliang/quickly-picture-bed/assets/158190203/69b70c4b-aa0e-48b7-85ef-e01a67d78d53) 这里面只有表结构，没有任何数据
